import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#e5e5e5",
        "surface": "#09090b",
        "on-primary": "#052e16",
        "on-error-container": "#ffdad6",
        "surface-variant": "#27272a",
        "inverse-primary": "#16a34a",
        "on-secondary": "#171717",
        "surface-container-highest": "#27272a",
        "on-tertiary": "#052e16",
        "on-secondary-fixed": "#171717",
        "on-background": "#e5e5e5",
        "surface-dim": "#09090b",
        "outline": "#52525b",
        "primary-fixed": "#bbf7d0",
        "tertiary-container": "#166534",
        "surface-bright": "#27272a",
        "primary": "#4ade80",
        "on-tertiary-fixed": "#052e16",
        "inverse-on-surface": "#d4d4d8",
        "on-tertiary-fixed-variant": "#14532d",
        "on-primary-fixed-variant": "#166534",
        "surface-container-lowest": "#000000",
        "outline-variant": "#3f3f46",
        "surface-container-low": "#18181b",
        "error": "#f87171",
        "tertiary-fixed-dim": "#22c55e",
        "on-secondary-fixed-variant": "#262626",
        "secondary-fixed-dim": "#a3a3a3",
        "tertiary-fixed": "#86efac",
        "secondary-container": "#27272a",
        "secondary-fixed": "#e5e5e5",
        "secondary": "#a3a3a3",
        "on-error": "#450a0a",
        "primary-container": "#166534",
        "on-primary-container": "#bbf7d0",
        "primary-fixed-dim": "#22c55e",
        "on-secondary-container": "#d4d4d8",
        "surface-container-high": "#27272a",
        "error-container": "#7f1d1d",
        "surface-container": "#18181b",
        "inverse-surface": "#e5e5e5",
        "on-surface-variant": "#a1a1aa",
        "on-tertiary-container": "#bbf7d0",
        "background": "#09090b",
        "on-primary-fixed": "#052e16",
        "surface-tint": "#4ade80",
        "tertiary": "#22c55e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit-xs": "4px",
        "unit-sm": "8px",
        "margin-desktop": "64px",
        "unit-md": "16px",
        "unit-lg": "32px",
        "container-max": "1200px",
        "unit-xl": "64px",
        "margin-mobile": "20px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-mono": ["var(--font-jetbrains)", "monospace"],
        "body-md": ["var(--font-geist)", "sans-serif"],
        "body-lg": ["var(--font-geist)", "sans-serif"],
        "display-lg-mobile": ["var(--font-geist)", "sans-serif"],
        "headline-md": ["var(--font-geist)", "sans-serif"],
        "display-lg": ["var(--font-geist)", "sans-serif"],
        "headline-lg": ["var(--font-geist)", "sans-serif"],
        "body": ["var(--font-geist)", "sans-serif"]
      },
      fontSize: {
        "label-mono": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg-mobile": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display-lg": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
};
export default config;
